name: clean_archtecture
description: A simple command-line application.

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  flutter:
    sdk: flutter
  flutter_modular: ^2.0.1
  dio: ^3.0.10
  dartz: ^0.9.2
  mockito: ^4.1.4
  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.9
  mobx_codegen: ^1.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
